
language: cpp
os: linux
dist: bionic
sudo: false

compiler:
  - gcc
addons:
  apt:
    packages:
    # compiler
      - cmake
      - g++-8
      - gcc-8
      - ninja-build
    # doc tools
      - doxygen
      - graphviz
      - mscgen
    # third-party dependencies
      - libboost-dev
      - libboost-date-time-dev
      - libboost-thread-dev
      - libboost-wave-dev
      - libboost-all-dev
env:
  - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && GCOV=gcov-8"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ${CXX} --version
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build-static-gcc && mkdir build-shared-gcc && mkdir build-bare-gcc && mkdir build-coverage-gcc
  - cd build-static-gcc
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
  - make
  - cd ../build-shared-gcc
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
  - make
  - cd ../build-bare-gcc
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DGB_BASE_BUILD_BARE=ON ..
  - make
  - cd ../build-coverage-gcc
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=OFF -DGB_GENERATE_COVERAGE_INFO=ON -DGCOV_COMMAND=${GCOV} ..
  - make
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd build-static-gcc
  - make test
  - cd ../build-shared-gcc
  - make test
  - cd ../build-bare-gcc
  - make test
  - cd ../build-coverage-gcc
  - make test

after_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd build-static-gcc
  - make doxygen-doc

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build-coverage-gcc
  - make gbBase_TestCoverage
  - bash <(curl -s https://codecov.io/bash)

